import type { Concept } from "@/data/concepts/types";

/** English concept sheets. */
export const conceptsEn: Concept[] = [
  {
    id: "c1",
    category: "valuation",
    title: "Enterprise Value vs Equity Value",
    simple:
      "EV is the value of the whole firm (equity holders + lenders). Equity Value is only the shareholders' claim. You bridge between them with net debt and a few balance-sheet items.",
    intuition:
      "Think of a house: the full purchase price (roof plus mortgage) is EV. What you actually own after the mortgage is Equity Value.",
    formula:
      "EV = Equity Value + Net Debt + Preferred Stock\n  + Minorities + Pension provisions − Associates",
    steps: [
      "Why EV in M&A? To compare companies with different leverage: EV/EBITDA looks at the business, not the capital structure.",
      "Canonical textbook formula: EV = Equity Value + Total Debt + Preferred Stock + Noncontrolling Interest − Cash. Pension provisions and associates are market extensions around that core.",
      "Equity → EV bridge: add debt (the buyer assumes it), preferred stock, minorities and pension provisions; subtract cash and associates.",
      "EV → Equity (price per share): reverse it — strip debt, preferred, minorities and pensions; add back cash and associates.",
    ],
    example: {
      label: "Quick example",
      body: "Equity Value 800, net debt 200, minorities 50, cash already netted in net debt → EV ≈ 800 + 200 + 50 = 1,050. Forgetting the +50 minorities breaks the bridge.",
    },
    interview:
      "The Equity ↔ EV bridge must be automatic. Missing minorities is still a deal-breaker mistake.",
    table: {
      headers: ["Item", "Logic", "Impact"],
      rows: [
        ["Financial debt", "Buyer will repay it", "+ EV"],
        ["Cash", "Buyer recovers it", "− EV"],
        ["Preferred stock", "Claim senior to common equity", "+ EV"],
        ["Minority interests", "Stake not owned", "+ EV"],
        ["Pension provisions", "Future obligation", "+ EV"],
        ["Associates (20-50%)", "Unconsolidated stake", "− EV"],
        ["IFRS 16 leases", "Operating debt", "+ EV (debated)"],
      ],
    },
    visual: "ev-bridge",
    pitfalls: [
      "Forgetting minorities in the bridge",
      "Forgetting preferred stock (standard line in the textbook formula, often skipped)",
      "Mixing 'available' cash with minimum operating cash",
      "Confusing gross debt and net debt",
      "Ignoring off-balance-sheet commitments (pensions, guarantees)",
    ],
  },
  {
    id: "c2",
    category: "dcf",
    title: "DCF (Discounted Cash Flow)",
    simple:
      "A DCF values a company by summing its future cash flows, discounted to today. A euro tomorrow is worth less than a euro today — you discount them at the WACC.",
    intuition:
      "What is the firm worth if we project its future cash and bring it back to today? That is the entire DCF logic.",
    formula: "EV = Σ FCFF(t) / (1+WACC)^t\n  + TV / (1+WACC)^n",
    steps: [
      "Project FCFF (cash generated by the business) over 5 years in general; up to 15-20 years for highly predictable / contractual revenue (utilities, concessions).",
      "Calculate the WACC, the discount rate.",
      "Discount each cash flow: the further out, the less it is worth.",
      "Calculate terminal value (cash beyond the explicit forecast).",
      "Mid-year convention: FCFF and the perpetuity-growth TV (PGM) are discounted mid-year; the exit-multiple TV (EMM) stays year-end, because it is based on year-end LTM multiples.",
      "Stress-test WACC, exit multiple and EBIT margins first, then g and revenue growth.",
      "Sum everything = EV, then subtract net debt for Equity Value.",
    ],
    example: {
      label: "Quick example",
      body: "Year-1 FCFF = 100, WACC = 10%. Present value ≈ 100 / 1.10 ≈ 91. The same cash flow in year 5 is worth only ~62. Terminal value (often 60–80% of EV) amplifies this — hence WACC / g sensitivities.",
    },
    interview:
      "Be able to walk through the steps aloud. Typical question: which variables to stress? WACC, exit multiple, EBIT margins — then g and revenue growth.",
    table: {
      headers: ["Component", "Formula", "Typical range"],
      rows: [
        ["FCFF", "EBIT × (1−t) + D&A − CapEx − ΔNWC", "Business-dependent"],
        ["WACC", "(E/V)×Ke + (D/V)×Kd×(1−t)", "6-12% for mid-caps"],
        ["Terminal value (Gordon)", "FCF × (1+g) / (WACC−g)", "60-80% of EV"],
        ["g (perpetual growth)", "Long-term growth", "1.5-3% (≤ inflation+1ppt)"],
        ["Explicit horizon", "Forecast period", "5 years (15-20 years if contractual revenue)"],
        ["Mid-year — PGM", "Perpetuity-growth TV", "Mid-year discounting"],
        ["Mid-year — EMM", "Exit-multiple TV (LTM)", "Year-end discounting"],
      ],
    },
    visual: "dcf-bridge",
    pitfalls: [
      "g above long-term economic growth",
      "Forgetting that NWC rises with revenue",
      "Underestimating maintenance CapEx",
      "Discounting at Ke instead of WACC",
      "Not testing multiple WACC / g assumptions",
      "Discounting EMM at mid-year: the LTM exit multiple stays year-end",
    ],
  },
  {
    id: "c3",
    category: "dcf",
    title: "WACC (Weighted Average Cost of Capital)",
    simple:
      "WACC is the blended return required by those who fund the firm: equity holders (Ke) and lenders (Kd). It is the discount rate used in a DCF.",
    intuition:
      "Two funders, two required returns: equity wants Ke, banks want Kd. WACC is the weighted average — and you discount FCFF at that rate.",
    formula: "WACC = (E/V) × Ke + (D/V) × Kd × (1 − t)",
    steps: [
      "Ke (cost of equity): CAPM = risk-free rate + β × equity risk premium.",
      "Kd (cost of debt): borrowing cost × (1 − tax rate) because interest is tax-deductible.",
      "Weight E/V and D/V at market value, never book value.",
      "For beta: comps → unlever → median → relever to target structure.",
    ],
    example: {
      label: "Quick example",
      body: "Equity €700m, Debt €300m → V = 1,000. Ke = 10%, Kd = 5%, tax = 25%. WACC = 70% × 10% + 30% × 5% × 0.75 = 7% + 1.125% = 8.125%.",
    },
    interview:
      "Always cite market weights, (1−t) on debt, and the unlever / relever beta path.",
    table: {
      headers: ["Component", "Source", "Typical level (2026)"],
      rows: [
        ["Rf (risk-free rate)", "10Y government bond", "~3.5-3.9% (2026)"],
        ["ERP (equity risk premium)", "Damodaran, Fernandez", "5-7%"],
        ["β unlevered", "Unlevered comps", "0.6 to 1.5"],
        ["Ke (CAPM)", "Rf + β × ERP", "8-14%"],
        ["Kd pre-tax", "Spread + Rf", "4-7% (IG), 7-12% (HY)"],
        ["Final WACC", "E/V, D/V weights", "6-12% for mid-caps"],
      ],
    },
    visual: "wacc-curve",
    pitfalls: [
      "Using book weights instead of market weights",
      "Taking a levered beta without unlevering first",
      "Forgetting the tax shield on debt (× (1−t))",
      "WACC too low for a high-risk target",
      "No country risk premium for overseas assets",
    ],
  },
  {
    id: "c4",
    category: "accounting",
    title: "The 3 Financial Statements and How They Link",
    simple:
      "Three statements to know: the income statement (gains and losses over a period), the balance sheet (a snapshot at a point in time), and the cash flow statement (cash in and out). They are linked.",
    intuition:
      "These are not three silos: net income, the balance sheet and cash talk to each other. If the loop closes, the model is consistent.",
    formula:
      "Net Income (P&L)  →  Equity (Balance Sheet)\nΔ Balance Sheet  →  Cash Flows (CFS)\nEnding Cash (CFS)  →  Cash (Balance Sheet)",
    steps: [
      "Net income from the P&L increases equity on the balance sheet.",
      "That same net income starts the cash flow statement (indirect method).",
      "Balance-sheet changes (inventory, receivables, PP&E, debt…) feed CFO, CFI and CFF.",
      "The cash change on the CFS explains the cash movement on the balance sheet.",
    ],
    example: {
      label: "Quick example",
      body: "CapEx €100: BS PP&E +100 / Cash −100, CFI −100, then D&A ~€20 in P&L the following year. Borrow €200: Cash +200 / Debt +200, CFF +200 — no direct hit to net income.",
    },
    interview:
      "Walking through a numbered example (CapEx, borrowing, dividend) across all three statements shows real mastery.",
    table: {
      headers: ["Action", "P&L impact", "Balance sheet impact", "Cash flow impact"],
      rows: [
        ["CapEx €100", "−€20 D&A (Y1)", "PP&E +100, Cash −100", "CFI −100"],
        ["NWC increase €50", "None directly", "NWC +50, Cash −50", "CFO −50"],
        ["Borrow €200", "−€10 interest (Y1)", "Cash +200, Debt +200", "CFF +200"],
        ["Dividends €30", "None (equity outflow)", "Cash −30, Equity −30", "CFF −30"],
        [
          "Provision €40",
          "Expense −€40 (NI −30 after 25% tax)",
          "Provision +40, Equity −30",
          "CFO non-cash (+40)",
        ],
      ],
    },
    visual: "3-statements",
    pitfalls: [
      "Forgetting that depreciation is non-cash (added back in CFO)",
      "Mixing NWC and CapEx",
      "Balance sheet that does not balance (assets ≠ liabilities + equity)",
      "Confusing net income with operating cash flow",
    ],
  },
  {
    id: "c5",
    category: "accounting",
    title: "NWC and the Cash Conversion Cycle",
    simple:
      "NWC is cash 'tied up' in day-to-day operations: inventory + receivables − payables. The higher it is, the more growth you must fund.",
    intuition:
      "Higher NWC means you need more cash to grow. A negative CCC (rare) means suppliers finance your customers — as in grocery retail.",
    formula:
      "NWC = Inventory + Receivables − Payables\nCCC = DIO + DSO − DPO",
    steps: [
      "DSO (days sales outstanding) = receivables / sales × 365.",
      "DIO (days inventory outstanding) = inventory / COGS × 365.",
      "DPO (days payable outstanding) = payables / COGS × 365.",
      "CCC = DIO + DSO − DPO: how long cash is locked in the cycle.",
    ],
    example: {
      label: "Quick example",
      body: "Classic industrials: DSO 60 + DIO 60 − DPO 60 = CCC 60 days. Amazon-style retail: DSO 5 + DIO 30 − DPO 80 = CCC −45 days — suppliers fund the cycle.",
    },
    interview:
      "In modelling: when revenue grows, NWC usually grows too — you must reflect that in the DCF.",
    table: {
      headers: ["Sector", "DSO", "DIO", "DPO", "CCC"],
      rows: [
        ["SaaS (cash upfront)", "30d", "0d", "30d", "0d or negative"],
        ["Retail (Amazon)", "5d", "30d", "80d", "−45d ✓"],
        ["Grocery (Carrefour)", "5d", "25d", "60d", "−30d ✓"],
        ["Classic industrials", "60d", "60d", "60d", "60d"],
        ["Construction", "90d", "30d", "45d", "75d"],
        ["Branded pharma", "100d", "120d", "60d", "160d"],
      ],
    },
    visual: "ccc-cycle",
    pitfalls: [
      "Confusing operating NWC with financial debt",
      "Ignoring seasonality (use a 12-month average)",
      "Including cash in the NWC calculation",
      "Not linking revenue growth to NWC growth",
    ],
  },
  {
    id: "c6",
    category: "lbo",
    title: "LBO (Leveraged Buy-Out)",
    simple:
      "An LBO buys a company largely with debt. A holdco borrows, acquires the target, then debt is repaid with cash generated by the business.",
    intuition:
      "The fund puts in some equity; banks provide the rest. The holdco borrows, buys, and repays with the target's cash — typical horizon 4 to 7 years.",
    formula: "IRR = (Equity Exit / Equity Entry)^(1/n) − 1\nMOIC = Equity Exit / Equity Entry",
    steps: [
      "Typical structure: 30–40% equity per the textbook (up to 50% depending on the credit cycle), the rest in debt.",
      "Create a holdco that borrows and buys the target; repay via cash flows / upstreamed dividends.",
      "Cash available for debt repayment = operating CF + investing CF (before financing). Mandatory amortisation first, then optional sweep.",
      "100% cash flow sweep: all cash left after mandatory repayments goes to optional repayment of prepayable debt (usually bank debt), in order Revolver → Term Loan A → Term Loan B.",
      "Term Loan B: standard amortisation ~1% of principal per year, remainder bullet at maturity. High yield (senior / sub notes): no mandatory amortisation, balance unchanged each year.",
      "Typical seniority / maturity (shortest to longest): Revolver → institutional Term Loan → Senior Notes → Senior Subordinated Notes.",
      "Interest: 'average interest expense' convention = average of beginning and ending debt balances, because debt is repaid during the year.",
      "Three value drivers: grow EBITDA, exit at a higher multiple, repay debt.",
    ],
    example: {
      label: "Quick example",
      body: "EV 100: Equity 40 + Debt 60. After 5 years, exit EV 150, debt paid down to 20 → equity exit 130. MOIC = 130/40 = 3.25×; IRR ≈ 27%.",
    },
    interview:
      "Explain structure, horizon, cash sweep and the three value levers — and do not forget NWC / CapEx. The book cites 30–40% equity as the reference range; in tighter recent credit markets (and high purchase multiples), you sometimes see up to 50%.",
    table: {
      headers: ["Component", "Typical %", "Cost", "Priority"],
      rows: [
        ["Equity (Sponsor + MEP)", "30-40% (textbook) / up to 50% by cycle", "Target IRR 20-25%", "Junior"],
        ["Senior Term Loan", "40-50%", "Euribor + 250-450 bps", "Senior 1"],
        ["Unitranche", "0-60%", "Euribor + 500-700 bps", "Senior 1 (hybrid)"],
        ["Mezzanine", "10-20%", "10-15% (cash + PIK)", "Junior secured"],
        ["RCF (revolving)", "For NWC", "Euribor + 200-300 bps", "Senior 1"],
      ],
    },
    visual: "lbo-structure",
    pitfalls: [
      "LBO on a highly cyclical target (unstable cash)",
      "Forgetting NWC or CapEx in the business plan",
      "Forgetting the cash sweep (100% of excess cash to prepayable bank debt)",
      "IRR calculated without transaction fees",
      "Overly optimistic exit multiple assumption",
    ],
  },
  {
    id: "c7",
    category: "lbo",
    title: "The Three LBO Value Creation Levers",
    simple:
      "LBO returns come from three sources: rising EBITDA, a higher exit multiple, and debt paydown. Knowing which dominates in your model is essential.",
    intuition:
      "Three ways to win: run the business better, sell for more, or pay down debt. Today, operations usually drive most of the return.",
    formula:
      "Δ Equity = Δ EBITDA × Entry Multiple\n  + Exit EBITDA × Δ Multiple\n  + Δ Net Debt",
    steps: [
      "Lever 1 — EBITDA growth (~50% of IRR): sales, margins, add-ons. Hardest, most valued.",
      "Lever 2 — Multiple expansion (~15–20%): sell at a higher multiple. Hard to control, market-driven. Modelling convention: exit multiple ≤ entry multiple, for conservatism.",
      "Lever 3 — Deleveraging (~30–35%): cash → debt repayment. At constant EV, equity rises.",
    ],
    example: {
      label: "Quick example",
      body: "Entry EV 800 (EBITDA 100 × 8×), debt 500 → equity 300. Exit: EBITDA 130 × 9× = EV 1,170, debt 200 → equity 970. Gains: EBITDA +240, multiple +130, deleveraging +300.",
    },
    interview:
      "Explaining which of the three levers dominates in a deal shows you understand the economics.",
    table: {
      headers: ["Lever", "% of IRR typical (2026)", "% of IRR 2000s", "Difficulty"],
      rows: [
        ["EBITDA growth", "~50%", "~25%", "High (execution)"],
        ["Multiple expansion", "~15-20%", "~15%", "Market-dependent"],
        ["Deleveraging", "~30-35%", "~60%", "Mechanical"],
      ],
    },
    visual: "lbo-value-bridge",
    pitfalls: [
      "Relying mainly on the exit multiple (uncertain)",
      "Assuming an exit multiple above the entry multiple without justification — the standard convention is exit multiple ≤ entry multiple, for conservatism.",
      "Underestimating time to improve EBITDA",
      "No add-on acquisitions in the plan",
      "Revenue growth without related CapEx or NWC",
    ],
  },
  {
    id: "c8",
    category: "valuation",
    title: "Valuation Multiples (EV/EBITDA, P/E, EV/Sales)",
    simple:
      "A multiple compares a company's value to a metric (EBITDA, sales, earnings). You look at what similar companies trade for to estimate a price.",
    intuition:
      "If peer firms trade at 8× EBITDA, applying that multiple to the target gives a first price indication — then cross-check with other methods.",
    formula: "Multiple = Value (EV or Equity Value)\n  / Metric (EBITDA, Sales, EPS, BV)",
    steps: [
      "EV/EBITDA: M&A standard, compares independent of leverage.",
      "EV/Sales: useful when not yet profitable (start-ups).",
      "P/E: useful for listed equities, less comparable in M&A (debt + tax).",
      "Consistency rule: an EV multiple must use a metric before interest (EBITDA, EBIT, Sales); an Equity Value multiple must use a metric after interest (Net Income, EPS). EV/Net Income and Equity Value/EBITDA are incorrect.",
      "Method: 5–10 comps → median → apply to target → cross-check several multiples.",
    ],
    example: {
      label: "Quick example",
      body: "Comps median = 8× EV/EBITDA. Target EBITDA €50m → EV ≈ €400m. Net debt €120m → Equity Value ≈ €280m.",
    },
    interview:
      "Always specify LTM vs NTM, and say whether you are quoting the median or the mean.",
    table: {
      headers: ["Multiple", "Use case", "Mid-cap industrials", "Tech/SaaS", "Banks"],
      rows: [
        ["EV/EBITDA", "Standard M&A", "6-9x", "15-25x", "N/A"],
        ["EV/Sales", "Unprofitable", "0.8-1.5x", "5-15x", "N/A"],
        ["EV/EBIT", "Capital-intensive", "8-12x", "20-30x", "N/A"],
        ["P/E", "Equity holders", "12-18x", "25-50x", "8-12x"],
        ["P/B", "Banks, REITs", "1.5-2.5x", "5-10x", "0.8-1.5x"],
        ["EV/FCF", "Free cash yield", "12-20x", "20-35x", "N/A"],
      ],
    },
    visual: "football-field",
    pitfalls: [
      "Comparing companies at very different stages",
      "Mixing trailing (LTM) and forward (NTM) data",
      "Forgetting adjustments (add-backs, IFRS 16)",
      "Too few comps or overly heterogeneous set",
      "Quoting a mean without also stating the median",
      "Mixing an equity metric (Net Income, EPS) with EV, or a firm metric (EBITDA, Sales) with Equity Value — numerator/denominator consistency is a classic oral trap.",
    ],
  },
  {
    id: "c9",
    category: "ts",
    title: "Quality of Earnings (QoE)",
    simple:
      "QoE seeks 'normal' EBITDA — the level you can expect every year. You strip one-offs to see the true underlying performance.",
    intuition:
      "M&A prices often rest on multiple × EBITDA. Each extra million of EBITDA at 8× is €8m of value — hence the hunt for add-backs.",
    formula:
      "Adjusted EBITDA = Reported EBITDA\n  ± Add-backs (non-recurring, non-operating, non-cash)",
    steps: [
      "Positive add-back: remove a one-off charge (restructuring, M&A fees, one-time litigation).",
      "Negative add-back: remove a one-off gain (asset sale, FX gain).",
      "Every line must be documented (invoice, contract).",
      "Beyond 15–20% of reported EBITDA, buyers get sceptical.",
    ],
    example: {
      label: "Quick example",
      body: "Reported EBITDA €40m + one-off redundancy plan €2m + M&A fees €1m → Adjusted EBITDA €43m. At 8×, +€3m EBITDA = +€24m EV.",
    },
    interview:
      "Be able to separate genuine one-shot add-backs from charges that recur every year.",
    table: {
      headers: ["Add-back type", "Example", "EBITDA impact", "Market acceptance"],
      rows: [
        ["Restructuring", "Redundancy plan €2m", "+€2m", "High (90%)"],
        ["Settled litigation", "One-off settlement", "+ amount", "High"],
        ["M&A fees", "Legal fees", "+€1m", "High"],
        ["Product launch", "One-shot marketing", "+ partial", "Medium (50%)"],
        ["Holdco management fees", "1% of sales", "+ removed", "High if arm's-length"],
        ["COVID impact", "Over/under-performance", "Debated", "Low (variable)"],
        ["IFRS 16 (leases)", "Rent → D&A+Interest", "Often adjusted", "Common practice"],
      ],
    },
    pitfalls: [
      "Add-backs that recur every year (not truly exceptional)",
      "No support per line item",
      "Adjusted EBITDA far above cash with no explanation",
      "Too many add-backs (>15-20% of EBITDA)",
    ],
  },
  {
    id: "c10",
    category: "ts",
    title: "Net Debt and Debt-like Items",
    simple:
      "Net debt determines what the buyer actually pays (Equity Value = EV − net debt). Every negotiated line can be worth millions.",
    intuition:
      "Anything the buyer must pay after closing, outside ordinary NWC, looks like debt — and reduces the price paid to sellers.",
    formula:
      "Net Debt = Financial Debt − Cash\n  + Debt-like − Cash-like",
    steps: [
      "Classic debt: loans, bonds, drawn RCF.",
      "Only 'true' cash: not trapped cash or minimum operating cash.",
      "Debt-like: pension deficits, earn-outs due, declared dividends, sometimes IFRS 16 leases.",
      "In the SPA, every net debt line is negotiated one by one.",
    ],
    example: {
      label: "Quick example",
      body: "EV 100. Loans 40, available cash 10, pensions 5, earn-out due 3 → net debt 38. Equity Value = 100 − 38 = €62m. Each million of debt-like = €1m less for the seller.",
    },
    interview:
      "Never put operating NWC into net debt (double-count with locked box / completion).",
    table: {
      headers: ["Item", "Category", "Logic"],
      rows: [
        ["Bank loans", "Pure debt", "Clear"],
        ["Issued bonds", "Pure debt", "Clear"],
        ["Drawn RCF", "Pure debt", "If > 0"],
        ["Cash and equivalents", "Cash", "Clear"],
        ["Trapped cash (overseas)", "Restricted", "Repatriation costs"],
        ["Minimum operating cash", "Restricted", "Not available"],
        ["Unfunded pension provisions", "Debt-like", "Future obligation"],
        ["Earn-outs on past periods", "Debt-like", "Certain future payment"],
        ["Dividends payable", "Debt-like", "Commitment"],
        ["IFRS 16 leases", "Debated", "Market practice: include"],
        ["Over-aged payables", "Debt-like", "Cash stress"],
        ["Positive shareholder current accounts", "Cash-like", "Recoverable"],
      ],
    },
    pitfalls: [
      "Forgetting guarantees and off-balance-sheet commitments",
      "Not all cash is available to the buyer",
      "Underestimating pension provisions",
      "Putting operating NWC into net debt (double-count)",
    ],
  },
  {
    id: "c11",
    category: "ma",
    title: "M&A Process — From Teaser to Closing",
    simple:
      "A company sale typically follows 7 to 8 steps over 6 to 12 months: preparation, buyer outreach, offers, due diligence, negotiation, signing, closing.",
    intuition:
      "This is not a sprint: 6 to 12 months, with a key distinction — signing ≠ closing (often 3 to 6 months between them).",
    formula:
      "Preparation → Marketing → Round 1 → DD\n  → Round 2 → Signing → Closing → Post-closing",
    steps: [
      "Preparation: IM + VDD (vendor due diligence).",
      "Marketing: anonymous teaser, then IM under NDA.",
      "Round 1: non-binding indicative offers.",
      "Short-list + dataroom / deep DD, then binding offers + SPA mark-up.",
      "Signing (legal commitment) then Closing (payment after conditions).",
    ],
    example: {
      label: "Quick example",
      body: "Typical mid-cap deal: M0–M2 prep, M3–M4 round 1, M4–M6 DD, M7 signing, M9–M12 closing after antitrust / financing.",
    },
    interview:
      "Never confuse signing and closing — and mention MAC clauses and locked box vs completion.",
    table: {
      headers: ["Phase", "Duration", "Key deliverable", "Lead actor"],
      rows: [
        ["Preparation", "M0-M2", "IM, teaser, VDD", "Sell-side bank"],
        ["Marketing", "M2-M3", "Signed NDAs", "Sell-side bank"],
        ["Round 1", "M3-M4", "Indicative offers", "Buyers"],
        ["Due diligence", "M4-M6", "DD reports", "Buyer advisers"],
        ["Round 2", "M6-M7", "Binding offers + SPA mark-up", "Buyers"],
        ["Signing", "M7", "Signed SPA", "Legal counsel"],
        ["Closing", "M9-M12", "Conditions satisfied, payment", "Banks + legal"],
        ["Post-closing", "M12+", "Price adjustment, integration", "Management"],
      ],
    },
    visual: "ma-process",
    pitfalls: [
      "Confusing signing and closing",
      "Underestimating antitrust timelines on large deals",
      "Ignoring the MAC clause (material adverse change)",
      "Not anticipating locked box vs completion accounts",
    ],
  },
  {
    id: "c12",
    category: "ma",
    title: "Locked Box vs Completion Accounts",
    simple:
      "Two ways to set the final price. Locked box: price fixed on a past balance sheet. Completion accounts: price adjusted at closing for actual net debt and NWC.",
    intuition:
      "Locked box = early certainty (Europe / PE). Completion = precision at closing, but more disputes (US).",
    formula:
      "Locked Box: price fixed at past date + ticking fee\nCompletion: price adjusted for Net Debt / NWC at closing",
    steps: [
      "Locked box: accounts as of a past date; no 'leakage' of value; ticking fee for the delay.",
      "Completion: recalculate net debt and NWC at closing — fairer, more post-deal audit.",
      "Choose based on target stability and regional practice.",
    ],
    example: {
      label: "Quick example",
      body: "Locked-box equity €80m at 31 Dec, closing 30 Jun, ticking 5%/year → ~€2m. Price ≈ €82m fixed. Under completion, €5m unexpected net debt → price €75m.",
    },
    interview:
      "One-liner: locked box = simplicity; completion = precision but complexity.",
    table: {
      headers: ["Criterion", "Locked Box", "Completion Accounts"],
      rows: [
        ["Reference date", "Past (3-6 months before)", "Closing date"],
        ["Price certainty", "High (from signing)", "Low (adjusted post-closing)"],
        ["Risk between signing and closing", "Buyer (ticking fee); leakage = seller", "Buyer"],
        ["Compensation", "Ticking fee (interest)", "None (actuals)"],
        ["Complexity", "Simpler, faster", "More complex, audit"],
        ["Disputes", "Limited", "Frequent"],
        ["Preferred region", "Europe (PE)", "US"],
        ["Targets", "Stable", "Volatile or complex"],
      ],
    },
    pitfalls: [
      "Poorly defined leakages in locked box",
      "Ticking fee too low for the seller",
      "Missing lines in net debt (completion)",
      "Bad estimate of normative NWC",
    ],
  },
  {
    id: "c13",
    category: "ma",
    title: "Synergies — Types and Valuation",
    simple:
      "Synergies are the extra value created after a combination: cost savings, cross-selling, etc. They often explain why the buyer pays a premium.",
    intuition:
      "Cost synergies are the most credible; revenue synergies sell well in a pitch but are realised less often.",
    formula:
      "NPV Synergies = Σ (Synergies × (1−t)\n  − Integration costs) / (1+WACC)^t",
    steps: [
      "Costs (70–90% realisation): overlaps, procurement, IT — 1–2 year timeline.",
      "Revenue (50–65%): cross-sell — 3–5 year timeline, riskier.",
      "Tax / financial: NOLs, WACC — more modest effects.",
      "Always net of integration costs (often 1–2× annual synergies).",
    ],
    example: {
      label: "Quick example",
      body: "Cost synergies €20m/year, integration costs €30m in year 1, tax 25%, WACC 8%. The NPV of these net cash flows justifies part of the premium paid.",
    },
    interview:
      "Never claim 100% of synergies in year 1 — and distinguish gross vs net.",
    table: {
      headers: ["Type", "Example", "Realisation rate", "Timeline"],
      rows: [
        ["Overhead costs", "HQ consolidation", "85-95%", "12-18 months"],
        ["Operating costs", "Joint sourcing", "70-85%", "24-36 months"],
        ["IT costs", "System consolidation", "60-75%", "24-48 months"],
        ["Cross-sell revenue", "New products", "50-65%", "36-60 months"],
        ["Geographic revenue", "New markets", "40-55%", "36-72 months"],
        ["Tax", "NOLs, structure", "Variable", "12-24 months"],
        ["Financial (WACC)", "Risk diversification", "Modest", "Long term"],
      ],
    },
    visual: "synergies-jcurve",
    pitfalls: [
      "Overestimating revenue synergies",
      "Forgetting integration costs",
      "Claiming all synergies from year 1",
      "No concrete plan (who, when, how much)",
      "Confusing gross and net synergies",
    ],
  },
  {
    id: "c14",
    category: "valuation",
    title: "CAPM and Beta Calculation",
    simple:
      "CAPM estimates what equity holders require: Ke = risk-free rate + β × equity risk premium. Beta measures whether the stock moves more or less than the market.",
    intuition:
      "β = 1 tracks the market; β > 1 is more volatile; β < 1 is more defensive. You almost never take the target's raw beta as-is.",
    formula:
      "Ke = Rf + β × (Rm − Rf)\n  + premia (size, country, illiquidity)",
    steps: [
      "Rf: a long-term government bond (10Y OAT in the euro area; in the US, interpolated ~20-year). Never a short-term money-market rate (Fed Funds, Euribor, LIBOR).",
      "Take listed comps.",
      "Unlever: β_u = β_l / (1 + (1−t) × D/E).",
      "Median unlevered β, then relever to target structure.",
      "Plug Ke into WACC; add a size premium for unlisted mid-caps.",
    ],
    example: {
      label: "Quick example",
      body: "Rf 3.5%, β 1.2, ERP 5.5% → Ke = 3.5% + 1.2 × 5.5% = 10.1%.",
    },
    interview:
      "Always cite the unlever / relever path — and a long-term government bond as Rf, never a short-term money-market rate.",
    table: {
      headers: ["Sector", "Typical β unlevered", "Typical β levered", "Profile"],
      rows: [
        ["Utilities", "0.4-0.6", "0.5-0.7", "Defensive"],
        ["Consumer staples", "0.5-0.7", "0.7-0.9", "Defensive"],
        ["Pharma", "0.6-0.9", "0.7-1.0", "Defensive"],
        ["Industrials", "0.8-1.1", "1.0-1.3", "Moderately cyclical"],
        ["Tech", "1.0-1.4", "1.1-1.5", "Cyclical"],
        ["Luxury", "1.0-1.3", "1.1-1.4", "Cyclical"],
        ["Auto", "1.1-1.5", "1.3-1.7", "Highly cyclical"],
        ["Banks", "0.8-1.2", "1.2-1.8", "Highly levered"],
        ["Mining / Commodities", "1.2-1.8", "1.3-2.0", "Highly cyclical"],
      ],
    },
    visual: "beta-sectors",
    pitfalls: [
      "Levered beta used without unlevering",
      "Using Fed Funds, Euribor or LIBOR as Rf instead of a long-term government bond",
      "Look-back period too short or too long",
      "No small-cap premium for a mid-cap",
      "Forgetting country risk overseas",
      "Negative beta without checking the data",
    ],
  },
  {
    id: "c15",
    category: "accounting",
    title: "EBITDA — Uses and Limits",
    simple:
      "EBITDA measures operating profitability before interest, tax and depreciation. It is the most used M&A metric, but it is not cash.",
    intuition:
      "We like it because it compares across different debt and tax setups — but it ignores CapEx, NWC and interest.",
    formula: "EBITDA = Operating Profit\n  + Depreciation + Amortisation",
    steps: [
      "Before interest → comparable across capital structures.",
      "Before tax → comparable across jurisdictions.",
      "Before D&A → neutralises depreciation policy choices.",
      "Always cross-check with CFO and CapEx: EBITDA ↑ + cash ↓ = red flag.",
    ],
    example: {
      label: "Quick example",
      body: "EBITDA €80m but CapEx 40 and ΔNWC +25 → operating cash is far lower than EBITDA suggests.",
    },
    interview:
      "Say 'EBITDA is not cash' and explain IFRS 16 (rent → D&A + interest).",
    table: {
      headers: ["Metric", "Includes", "Excludes", "Use"],
      rows: [
        [
          "EBITDA",
          "Core operations",
          "Interest, tax, D&A, NWC, CapEx",
          "Valuation multiples",
        ],
        [
          "EBITDA − CapEx",
          "Same + maintenance CapEx",
          "Interest, tax, NWC, growth CapEx",
          "Heavy industry",
        ],
        ["EBIT", "Operations + D&A", "Interest, tax, NWC, CapEx", "ROCE, alternative valuation"],
        ["CFO (Operating Cash Flow)", "Cash actually generated", "CapEx, financing", "Cash reality"],
        ["FCFF", "CFO + interest × (1−t) − CapEx", "None (cash to firm)", "DCF"],
        [
          "FCFE",
          "FCFF − interest × (1−t) + net borrowing",
          "Cash to equity only",
          "DDM, equity valuation",
        ],
      ],
    },
    pitfalls: [
      "Confusing EBITDA with cash",
      "Comparing reported and adjusted EBITDA",
      "Forgetting the IFRS 16 effect (rent → D&A + interest)",
      "Positive EBITDA but negative cash (NWC)",
      "High EBITDA margin but low ROCE",
    ],
  },
  {
    id: "c16",
    category: "valuation",
    title: "DDM — Gordon, Two-Stage and H-Model",
    simple:
      "A DDM values a share by summing future dividends, discounted to today. Useful for banks, insurers and utilities, where dividends are stable and clearer than free cash flows.",
    intuition:
      "When dividends are predictable (banks, utilities), discounting them can be clearer than a classic DCF.",
    formula:
      "Gordon: P0 = D1 / (Ke − g)\nTwo-stage: Σ Dt/(1+Ke)^t + Pn/(1+Ke)^n",
    steps: [
      "Gordon: constant growth g < Ke — mature companies only.",
      "Two-stage: explicit forecast then terminal Gordon — banks in transition.",
      "H-model: g declines linearly from gs to gl — avoids a sharp cliff.",
      "Ke comes from CAPM; the DDM gives Equity Value directly.",
    ],
    example: {
      label: "Quick example",
      body: "D1 = €2, Ke = 8%, g = 2% → P0 = 2 / 0.06 = €33.3. If g = 3%, P0 = €40 — extreme sensitivity to g.",
    },
    interview:
      "Never apply Gordon to a no-dividend tech name; stress that g < Ke or the model breaks.",
    table: {
      headers: ["Model", "Key assumption", "Typical sector", "Trap"],
      rows: [
        ["Gordon", "Constant g, g < Ke", "Mature utility, REIT", "g too high"],
        ["Two-stage", "Explicit growth then stable", "Bank in transition", "Mis-calibrated TV"],
        ["H-model", "g declines linearly", "Utility ramping dividend", "H poorly estimated"],
        ["DDM vs DCF", "Dividends vs FCFF", "FIG / utilities", "Payout ≠ 100% FCF"],
      ],
    },
    pitfalls: [
      "g ≥ Ke (invalid model)",
      "Applying Gordon to high-growth tech with no dividend",
      "Forgetting DDM gives Equity Value directly (not EV)",
      "Unsustainable long-term payout ratio",
      "Ke inconsistent with sector beta",
    ],
  },
  {
    id: "c17",
    category: "ma",
    title: "IPO Process — Book-building, Greenshoe, Lock-up",
    simple:
      "An IPO lists a private company on the public market. Price is set via book-building (investor order books). The greenshoe helps stabilise the share price; the lock-up stops insiders dumping stock immediately.",
    intuition:
      "The market 'votes' the price during book-building. Greenshoe and lock-up keep the first trading days from going off the rails.",
    formula:
      "Float = Shares sold / Post-IPO capital\nGreenshoe = +15% max (over-allotment)",
    steps: [
      "Preparation: audit, prospectus, exchange choice (6–9 months).",
      "Roadshow then book-building: price × quantity orders.",
      "Pricing & allocation, first day of trading.",
      "Greenshoe (~15%) to stabilise; lock-up 90–180 days for insiders.",
    ],
    example: {
      label: "Quick example",
      body: "Dual track: IPO run in parallel with an M&A process to maximise tension. Lineage Logistics (2024) — large US cold-storage IPO with a heavy institutional book.",
    },
    interview:
      "Distinguish offer price and first trade (pop); cite greenshoe and lock-up without mixing them up.",
    table: {
      headers: ["Element", "Role", "Duration / size", "Audience"],
      rows: [
        ["Book-building", "Price-demand discovery", "1-2 weeks", "Institutions"],
        ["Indicative range", "Pricing guide", "±10-15% of final price", "Market"],
        ["Greenshoe", "Price stabilisation", "Up to +15% shares", "Lead syndicate"],
        ["Lock-up", "Insider sale ban", "90-180 days", "Founders, PE"],
        ["Dual track", "IPO vs M&A in parallel", "Full process", "PE/strategic seller"],
        ["Float", "Public liquidity", "15-30% typical mid-cap", "Public investors"],
      ],
    },
    visual: "ipo-process",
    pitfalls: [
      "Confusing offer price and first trading price (pop)",
      "Forgetting fees (underwriting ~3-7%)",
      "Ignoring lock-up when assessing true float",
      "Dual track without aligned NDAs and timelines",
    ],
  },
  {
    id: "c18",
    category: "ma",
    title: "Squeeze-out, Takeover Offers and Exchange Offers",
    simple:
      "Cash takeover (OPA in France): cash offer for control (30% trigger in France). Exchange offer (OPE): same logic, paid in shares. Squeeze-out: once at 90%, you can force remaining minorities to sell. To delist, you typically run a squeeze-out tender (OPR) then squeeze-out.",
    intuition:
      "Cash offer = cash, exchange offer = stock, squeeze-out = force at 90%. An exchange offer alone does not delist — that is OPR + squeeze-out.",
    formula:
      "Cash / exchange offer: 30% threshold (FR trigger)\nSqueeze-out: 90% of capital or votes (PACTE)",
    steps: [
      "Cash takeover: control paid in cash, premium often 20–40% vs share price.",
      "Exchange offer: control paid in acquirer shares — preserves cash.",
      "At ≥ 90%: squeeze-out tender then squeeze-out to force minorities / delist.",
      "Acquisition = control; merger = legal combination (often 'merger' = acquisition + premium).",
    ],
    example: {
      label: "Quick example",
      body: "UniCredit / Commerzbank: hostile cash offer. After a successful offer to 90%, squeeze-out can simplify the capital structure.",
    },
    interview:
      "Never confuse an exchange offer with delisting mechanics — citing a recent deal helps.",
    table: {
      headers: ["Mechanism", "Objective", "Key threshold", "Typical example"],
      rows: [
        ["Cash takeover (OPA)", "Control (cash consideration)", "30% trigger (FR)", "UniCredit/CBK"],
        ["Exchange offer (OPE)", "Control (stock consideration)", "30% trigger (FR)", "Cross-border exchange offer"],
        ["Friendly takeover", "Target board support", "Negotiated", "L'Oréal/Aesop"],
        ["Squeeze-out tender + Squeeze-out", "Force minorities / delist", "90% capital or votes", "Group simplification"],
        ["Merger", "Combined entities", "2/3 AGM approval", "UBS/CS (emergency)"],
        ["Acquisition", "Purchase of control", "Variable", "Most deals"],
      ],
    },
    pitfalls: [
      "Confusing exchange offer (stock) with delisting squeeze-out",
      "Forgetting the minimum regulatory premium",
      "Ignoring German vs French thresholds in a cross-border deal",
      "Squeeze-out impossible if thresholds not met",
    ],
  },
  {
    id: "c19",
    category: "ma",
    title: "Earn-out, Vendor Loan and Revenue-based Pricing",
    simple:
      "Three ways to adjust price after closing: earn-out (I pay you if you perform), vendor loan (I pay you later with interest), revenue-based pricing (price tracks revenue).",
    intuition:
      "When buyer and seller disagree on value, you defer part of the price into the future — contingent or interest-bearing.",
    formula:
      "Price = Upfront + Earn-out + Vendor Loan\nRBP: Price = f(future revenue)",
    steps: [
      "Earn-out: paid if KPIs are hit (1–5 years) — risk of buyer 'managing' the KPIs.",
      "Vendor loan: deferred seller credit (10–30%), subordinated, rate ~4–8%.",
      "RBP: indexed to revenue — common in early-stage SaaS.",
      "Often combined: e.g. 70% upfront + 20% earn-out + 10% vendor loan.",
    ],
    example: {
      label: "Quick example",
      body: "Deal 100: 70 cash at closing, 20 earn-out on years 2–3 EBITDA, 10 vendor loan over 3 years at 6%. The seller stays exposed to performance.",
    },
    interview:
      "Distinguish past-period earn-outs (debt-like in Net Debt) from future earn-outs (price component).",
    table: {
      headers: ["Mechanism", "Trigger", "Who bears risk", "Disputes"],
      rows: [
        ["Earn-out", "Future KPIs (EBITDA, revenue)", "Seller (performance)", "Very frequent"],
        ["Vendor Loan", "Contractual schedule", "Seller (credit)", "Moderate"],
        ["RBP", "Realised revenue", "Seller (volume)", "Revenue definition"],
        ["Escrow", "Indemnity claims", "Seller (held back)", "Post-closing"],
        ["CVR", "Market event (biotech)", "Buyer (option)", "Pharma-specific"],
      ],
    },
    pitfalls: [
      "Poorly documented earn-out (#1 post-deal dispute source)",
      "Vendor loan without clear subordination",
      "RBP with overly broad revenue definition (consolidated vs standalone)",
      "Confusing past earn-out (debt-like) and future earn-out (price)",
    ],
  },
  {
    id: "c20",
    category: "dcf",
    title: "Net Income → Free Cash Flow Bridge",
    simple:
      "The bridge links accounting net income to cash actually available. It is the foundation of a DCF: start from the P&L, strip non-cash items and fold in investment.",
    intuition:
      "Net income is not cash. Add back non-cash, subtract NWC and CapEx, then adjust interest to get to FCFF.",
    formula:
      "FCFF = NI + D&A − ΔNWC − CapEx + Int.(1−t)\nor: EBIT×(1−t) + D&A − CapEx − ΔNWC",
    steps: [
      "Start from Net Income.",
      "+ D&A (non-cash).",
      "− Δ NWC (increase = cash outflow).",
      "− CapEx.",
      "+ Interest × (1−t) to move to a firm view = FCFF.",
    ],
    example: {
      label: "Quick example",
      body: "NI 50 + D&A 20 − ΔNWC 15 − CapEx 25 + 8 × 0.75 = 36. Despite NI of 50, firm cash is only 36.",
    },
    interview:
      "Do not confuse FCFF (WACC) and FCFE (Ke) — and make the bridge close with the 3 statements.",
    table: {
      headers: ["Step", "Cash impact", "Non-cash?", "Common miss"],
      rows: [
        ["Net Income", "Starting point", "—", "—"],
        ["+ D&A", "Add-back", "Yes", "Non-cash provisions"],
        ["− Δ NWC", "If NWC ↑ = outflow", "No", "Seasonality"],
        ["− CapEx", "Outflow", "No", "Maintenance vs growth"],
        ["+ Int.(1−t)", "FCFF reclass", "No", "Discount at WACC"],
        ["= FCFF", "DCF base", "—", "Confusing with FCFE"],
      ],
    },
    visual: "ni-fcff-bridge",
    pitfalls: [
      "Forgetting Δ NWC in a high-growth company",
      "Confusing FCFF (WACC) and FCFE (Ke)",
      "CapEx = D&A in perpetuity without checking the sector",
      "Double-counting interest",
    ],
  },
  {
    id: "c21",
    category: "valuation",
    title: "Football Field — Valuation Summary",
    simple:
      "A football field stacks valuation ranges from each method (DCF, comps, transactions, LBO). You do not defend a single price: you show where the methods overlap.",
    intuition:
      "Valuation is not an exact science. You show where DCF, comps and deals overlap — that is the 'defendable' zone.",
    formula:
      "Fair value = overlap zone\nBar width = method sensitivity",
    steps: [
      "Show 4–5 methods: DCF, trading comps, deal comps, LBO (± DDM / brokers).",
      "Each bar = a range (sensitivities), not a point.",
      "Read the common zone as the board range.",
      "Exclude irrelevant methods rather than down-weighting them.",
    ],
    example: {
      label: "Quick example",
      body: "DCF 90–120, trading 95–110, deals 100–130, LBO 85–105 → common zone ~100–105. A DCF bar of 70–150 signals overly sensitive assumptions.",
    },
    interview:
      "Never present a single price; date the valuation and justify exclusions.",
    table: {
      headers: ["Method", "Low end", "High end", "When to exclude"],
      rows: [
        ["DCF", "High WACC, low g", "Low WACC, high g", "Weak cash-flow data"],
        ["Trading comps", "Median − discount", "Median + premium", "No peers"],
        ["Deal comps", "Transactions − premium", "Transactions + premium", "Few recent deals"],
        ["LBO", "IRR 25%+", "IRR 18-20%", "Target not LBO-able"],
        ["DDM", "High Ke", "Low Ke", "Outside FIG/utilities"],
        ["NAV", "Adjusted net assets", "Liquidation", "Holding, property co"],
      ],
    },
    visual: "football-field",
    pitfalls: [
      "Presenting a single point instead of a range",
      "Mixing valuation dates across methods",
      "Including irrelevant methods to look 'serious'",
      "Forgetting the control premium in trading comps",
    ],
  },
  {
    id: "c22",
    category: "ma",
    title: "Restructuring and Distressed M&A",
    simple:
      "When debt exceeds firm value, equity is worth little. You restructure the debt (often swapping claims for equity) or sell assets at distressed prices.",
    intuition:
      "If EV < total debt, equity is ~0. Creditors become the real decision-makers.",
    formula:
      "EV < Total Debt → equity ≈ 0\nDebt-for-equity: creditors → shareholders",
    steps: [
      "Insufficient cash / broken covenants → distress.",
      "Waterfall: seniors recover first; juniors and equity are diluted or wiped out.",
      "Debt-for-equity or distressed asset sale (often free and clear of some debt).",
      "Know Chapter 11 (US), scheme (UK), sauvegarde / conciliation (FR).",
    ],
    example: {
      label: "Quick example",
      body: "Going-concern EV 80, debt 120 → equity = 0. Seniors (80) take all value; juniors and old equity are wiped or diluted.",
    },
    interview:
      "Never value equity as if it were going concern; cite the creditor waterfall.",
    table: {
      headers: ["Mechanism", "Jurisdiction", "Who loses", "Who wins"],
      rows: [
        ["Chapter 11", "US", "Equity, juniors", "Senior, DIP lenders"],
        ["Scheme of arrangement", "UK", "Diluted equity", "Voting creditors"],
        ["Conciliation / sauvegarde", "France", "Shareholders", "Continuation plan"],
        ["Debt-for-equity", "All", "Old equity", "Converted creditors"],
        ["363 sale (asset)", "US", "Residual debt", "Asset buyer"],
        ["Stalking horse", "US/EU", "—", "Reference bidder"],
      ],
    },
    visual: "distressed-waterfall",
    pitfalls: [
      "Valuing equity as if going concern",
      "Ignoring the creditor waterfall (senior vs sub vs holdco)",
      "Confusing operational and financial restructuring",
      "Forgetting inter-creditor litigation risk",
    ],
  },
  {
    id: "c23",
    category: "accounting",
    title: "IFRS vs US GAAP — 10 Key Differences",
    simple:
      "IFRS (Europe) and US GAAP (United States) are two accounting 'languages'. They diverge most on leases, R&D and some cash-flow items. In M&A, that changes EBITDA, net debt and therefore price.",
    intuition:
      "Same business, two standards → different EBITDA and net debt. IFRS 16 (leases) is the gap most negotiated in SPAs.",
    formula:
      "Accounting gap → QoE / Net Debt bridge\n→ impact on EBITDA, FCF, multiples",
    steps: [
      "Identify the reporting standard (US GAAP vs IFRS).",
      "Bridge key gaps: leases, R&D, SBC, cash classification.",
      "IFRS 16: rent leaves EBITDA; lease debt hits the balance sheet.",
      "Then run QoE / Net Debt as usual.",
    ],
    example: {
      label: "Quick example",
      body: "Rent €10m/year. Before: EBITDA −10. After IFRS 16: EBITDA +10, but +€40–60m lease debt. Multiples and Net Debt shift overnight.",
    },
    interview:
      "On a US/EU cross-border deal, always state which standard the target's accounts follow.",
    table: {
      headers: ["Topic", "IFRS", "US GAAP", "M&A impact"],
      rows: [
        [
          "Goodwill",
          "No amortisation — annual impairment test (IAS 36)",
          "Same post-2001 (impairment only)",
          "PPA and impairment tests",
        ],
        [
          "R&D",
          "Research expensed; development capitalisable if PIRATE criteria (IAS 38)",
          "R&D expensed except internal software (ASC 350-40)",
          "Adjusted EBITDA, intangibles",
        ],
        [
          "Leases",
          "IFRS 16: almost everything on balance sheet (debt + ROU)",
          "ASC 842: similar but US thresholds and exemptions",
          "Net debt, EBITDA (rent → D&A + interest)",
        ],
        [
          "Revenue",
          "IFRS 15 — 5 steps, control of good/service",
          "ASC 606 — conceptually aligned",
          "ARR vs IFRS 15 revenue, long-term contracts",
        ],
        [
          "Interest (CFO)",
          "Choice: interest paid often in CFO or CFF",
          "Interest paid in CFO (strict rule)",
          "Cross-border CFO comparability",
        ],
        [
          "Impairment",
          "Recoverable amount test (max fair value less costs / VIU)",
          "Two-step goodwill test (ASC 350)",
          "One-off charges, QoE",
        ],
        [
          "Stock options",
          "IFRS 2 — grant-date fair value, graded",
          "ASC 718 — similar model",
          "Diluted EPS, non-cash bridge",
        ],
        [
          "Joint ventures",
          "Equity method (IAS 28) — no proportionate consolidation",
          "Equity method (ASC 323)",
          "Consolidation, perimeter",
        ],
        [
          "Cash flow",
          "Indirect method standard; flexibility on interest/dividends",
          "More prescriptive rules (ASC 230)",
          "NI → FCF bridge",
        ],
        [
          "Presentation",
          "No mandated P&L format (by nature or function)",
          "SEC: specific lines (operating income…)",
          "US vs EU comps",
        ],
      ],
    },
    pitfalls: [
      "Applying US multiples to IFRS accounts without bridging",
      "Forgetting IFRS 16 in net debt",
      "Confusing ARR (business metric) with IFRS 15 revenue",
      "Assuming goodwill is amortised under IFRS",
    ],
  },
  {
    id: "c24",
    category: "valuation",
    title: "Treasury Stock Method (TSM) and Diluted Shares",
    simple:
      "The TSM calculates how many extra shares would exist if all in-the-money option holders exercised. The cash proceeds are assumed to buy back shares at the current price — only the net balance (shares issued − shares bought back) actually dilutes the capital.",
    intuition:
      "An in-the-money option (exercise price < current share price) creates new shares. But exercise brings cash into the company, which can buy shares back — so net dilution is lower than the gross option count.",
    formula:
      "Net new shares = In-the-money options − (Total exercise proceeds / Current share price)\nDiluted shares = Basic shares + Net new shares (options) + Net new shares (convertibles)\nNSS: Conversion value = Underlying shares × Current share price\nExcess = Conversion value − Convertible par amount\nNSS net shares = Excess / Current share price",
    steps: [
      "Identify in-the-money option tranches only (exercise price < current price) — ignore the rest.",
      "Calculate total exercise proceeds (Σ exercise price × number of in-the-money options).",
      "Divide that proceeds figure by the current share price to get the theoretical shares bought back.",
      "Net new shares = in-the-money shares − shares bought back.",
      "For convertibles: choose between the if-converted method and net share settlement (NSS) as the case requires — implied share price creates circularity (price depends on diluted shares, which depend on price): turn on Excel iteration to solve it.",
    ],
    example: {
      label: "Quick example",
      body: "20m options, exercise price €10, current price €25. Exercise proceeds = €200m. Shares bought back = €200m/€25 = 8m. Net new shares = 20m − 8m = 12m. NSS: €225m convertible, conversion price €22.50 → 10m underlying shares. Current price €30 → conversion value €300m. Excess = 300 − 225 = €75m. NSS net shares = €75m/€30 = 2.5m (vs 10m if-converted — NSS is almost always less dilutive).",
    },
    interview:
      "Always check the option is in-the-money before including it — an out-of-the-money option is never dilutive. And if the calc loops (price depends on diluted shares), that is normal: it is a classic circular reference, not a model error.",
    table: {
      headers: ["Method", "Instrument", "Logic"],
      rows: [
        ["TSM", "Options / warrants", "Theoretical buyback at the current price with exercise proceeds"],
        ["If-converted", "Convertibles", "Full conversion, add the underlying shares at par"],
        [
          "Net Share Settlement (NSS)",
          "Convertibles",
          "Only the excess (conversion value − par amount) becomes shares",
        ],
      ],
    },
    pitfalls: [
      "Including out-of-the-money options (exercise price > current price)",
      "Forgetting to apply exercise proceeds before computing shares bought back",
      "Confusing the if-converted method (full conversion) with net share settlement (only the excess becomes shares) — the dilution gap can be large",
      "Not handling the circularity implied share price ↔ diluted shares (turn on Excel iteration)",
    ],
  },
  {
    id: "c25",
    category: "valuation",
    title: "Premium Paid Analysis",
    simple:
      "Premium paid measures how much more the buyer pays versus the target's unaffected share price, in %. It is the premium the buyer accepts to pay for control.",
    intuition:
      "The share price just before announcement has often already moved (leaks, rumours) — you then have to go back to a clean, unaffected price not driven by deal anticipation.",
    formula:
      "% Premium Paid = (Offer Price per Share / Unaffected Share Price) − 1\nEquity Value = Unaffected price × (1 + Premium) × Diluted shares\nEV = Equity Value + Debt + Preferred + Minorities − Cash",
    steps: [
      "Identify the unaffected price — typically measured 1, 7 and 30 days before announcement.",
      "Check that no leak, rumour or strategic-review announcement had already moved the price on those dates.",
      "If it had, go further back to find a truly clean price.",
      "Compute the premium on each horizon (1d / 7d / 30d) to give a range, not a single figure.",
      "Combine with the Equity → EV bridge (c1): Equity Value = Unaffected price × (1 + Premium) × Diluted shares; EV = Equity Value + Debt + Preferred + Minorities − Cash.",
    ],
    example: {
      label: "Quick example",
      body: "Offer €20/share. Price 1 day before announcement: €17.39 (already a 15% premium — likely a leak). Price 30 days before (unaffected): €14.60 → true premium 37%. The 15% vs 37% gap flags an information leak before the official announcement.",
    },
    interview:
      "Always state which horizon (1d/7d/30d) the premium is calculated on, and why the '1 day before' price can mislead if there was a leak.",
    table: {
      headers: ["Factor", "Effect on the premium", "Explanation"],
      rows: [
        ["Hostile deal", "↑", "Tender offer straight to shareholders, topping-bid risk"],
        ["Leak / rumour before announcement", "Price already inflated", "Use an older price as the reference"],
        [
          "Strategic buyer with synergies",
          "↑",
          "Ability to pay more because of extra value creation",
        ],
        ["Distressed target / forced sale", "↓", "Weaker seller negotiating power"],
        [
          "Merger-of-equals (MOE)",
          "↓↓",
          "Typically 100% stock consideration, a low premium versus a classic takeover",
        ],
      ],
    },
    pitfalls: [
      "Using the '1 day before announcement' price without checking it had not already reacted to a leak",
      "Quoting a single premium figure instead of a range (1d/7d/30d)",
      "Running a premium paid analysis on an unlisted target (not relevant)",
      "Confusing the control premium with the total premium (which also includes anticipated synergies)",
      "Applying takeover-premium logic to a merger-of-equals, where the premium is structurally lower",
    ],
  },
  {
    id: "c26",
    category: "ma",
    title: "Accretion / Dilution Analysis",
    simple:
      "A deal is accretive if the acquirer's EPS rises after the transaction, dilutive if it falls. Listed strategic buyers almost always run this test before signing off on a deal.",
    intuition:
      "You compare pro forma EPS (after the merger) with the acquirer's standalone EPS. If the combined entity earns more net income per share than before, the market reads it as a positive signal.",
    formula:
      "Pro forma combined EPS = Pro forma combined net income / Pro forma diluted shares\nAccretion/(Dilution) $ = Pro forma combined EPS − Acquirer standalone EPS\nAccretion/(Dilution) % = (Pro forma combined EPS / Acquirer standalone EPS) − 1\nPre-tax synergies to breakeven = − (Accretion/(Dilution) $ × Pro forma diluted shares) / (1 − tax rate)",
    steps: [
      "Compute pro forma combined net income (acquirer earnings + target earnings + synergies − extra interest expense from deal financing − extra D&A on asset write-ups).",
      "Compute pro forma diluted shares (acquirer shares + new shares issued if stock consideration).",
      "Pro forma combined EPS = combined net income / pro forma diluted shares.",
      "Compare with the acquirer's standalone EPS → accretive if higher, dilutive if lower.",
      "If dilutive, compute the pre-tax synergies needed to reach breakeven.",
      "Identify the three funding sources — available cash, debt, stock — and the trade-offs: cost of capital, balance-sheet flexibility, rating-agency views, speed/certainty of closing.",
    ],
    example: {
      label: "Quick example",
      body: "Combined net income 1,000, pro forma diluted shares 250m → EPS €4.00. Acquirer standalone EPS €3.50. Accretion = +€0.50 (+14.3%) → accretive deal.",
    },
    interview:
      "Quick rule for an all-stock deal: if the acquirer's P/E is higher than the target's, the deal is mechanically accretive (and vice versa). But accretive ≠ value-creating: a deal can stay dilutive at first and still be justified if synergies are credible, the asset is strategic, or more stock protects the rating. The DCF/NPV test remains the economic judge.",
    table: {
      headers: ["Driver", "Effect on accretion"],
      rows: [
        ["Lower purchase price", "↑ accretive"],
        ["Cash/cheap debt financing rather than stock", "↑ accretive (no new shares issued)"],
        ["Acquirer P/E > target P/E (all-stock deal)", "↑ accretive"],
        ["High, fast synergies", "↑ accretive"],
        ["High cost of debt", "↓ dilutive"],
        [
          "Raise the stock mix to protect the credit rating",
          "↓ dilutive near term, but protects the balance sheet",
        ],
      ],
    },
    pitfalls: [
      "Focusing only on accretion/dilution without looking at real value creation (a deal can be accretive yet value-destructive, and vice versa)",
      "Forgetting extra interest expense from acquisition debt",
      "Forgetting amortisation of intangible write-ups in pro forma earnings",
      "Confusing accretion/dilution (an accounting EPS test) with DCF value creation (an economic test)",
      "Ignoring that contribution analysis (share of sales/EBITDA/net income/equity value contributed by each party) is the reference tool for a merger-of-equals, distinct from classic accretion/dilution",
    ],
  },
  {
    id: "c27",
    category: "lbo",
    title: "Credit Ratios and Debt Seniority",
    simple:
      "Credit ratios measure a company's ability to carry and repay debt. They determine how much leverage a lender will allow in an LBO, and split into two families: leverage ratios (debt vs cash flow) and coverage ratios (ability to pay interest).",
    intuition:
      "A lender does not only ask 'what is it worth' but 'how much can it repay each year'. Two firms with the same EV can support very different debt levels depending on cash generation.",
    formula:
      "Leverage: Debt / EBITDA, Senior secured debt / EBITDA, Net debt / EBITDA\nCoverage: EBITDA / Interest, (EBITDA − CapEx) / Interest, EBIT / Interest",
    steps: [
      "Senior secured debt / EBITDA: priority leverage, what senior bank lenders look at first.",
      "Total debt / EBITDA: overall leverage of the structure, including subordinated / high yield.",
      "EBITDA / Interest (interest coverage): the higher it is, the sturdier the structure — a low ratio flags default risk on interest.",
      "(EBITDA − CapEx) / Interest: stricter version, strips CapEx before measuring interest-paying ability — relevant for capital-intensive businesses.",
      "These ratios are read over time: a successful LBO sees leverage fall and coverage rise (deleveraging).",
    ],
    example: {
      label: "Quick example",
      body: "LTM EBITDA 700, interest 248.5, senior secured debt 2,800, total debt 3,650. EBITDA/Interest = 2.8x. Senior debt/EBITDA = 4.0x. Total debt/EBITDA = 5.2x.",
    },
    interview:
      "Average LBO leverage swings with the credit cycle: ~3.9x in 2002, up to 6.1x at the 2007 peak, 4.0x in 2009, then ~6.0x in 2018. Placing today's cycle in that range shows real market culture.",
    table: {
      headers: ["Ratio", "Formula", "What it measures"],
      rows: [
        [
          "Senior secured debt / EBITDA",
          "Senior secured debt / EBITDA",
          "Priority leverage — what bank lenders look at first",
        ],
        ["Total debt / EBITDA", "Total debt / EBITDA", "Overall leverage of the structure"],
        ["Net debt / EBITDA", "(Total debt − Cash) / EBITDA", "Leverage net of available cash"],
        ["EBITDA / Interest", "EBITDA / Interest expense", "Ability to cover interest"],
        [
          "(EBITDA − CapEx) / Interest",
          "(EBITDA − CapEx) / Interest expense",
          "Stricter version for capital-intensive businesses",
        ],
        [
          "Debt-to-Total Cap.",
          "Debt / (Debt + Equity)",
          "Debt weight in the overall financing structure",
        ],
      ],
    },
    pitfalls: [
      "Confusing senior secured/EBITDA (priority leverage) with total debt/EBITDA (overall leverage) — two covenants, two thresholds",
      "Using gross EBITDA without subtracting CapEx in a highly capital-intensive sector",
      "Ignoring the credit cycle — the same leverage does not mean the same thing in 2007 as in 2009",
      "Forgetting that coverage ratios should improve over time (otherwise a covenant warning)",
    ],
  },
  {
    id: "c28",
    category: "lbo",
    title: "LBO Debt Instruments: Seniority, Covenants and Maturity",
    simple:
      "In an LBO, not all creditors are equal: some are repaid first (senior secured), others later (subordinated), and some lenders sit structurally behind others depending on which legal entity holds the debt (OpCo vs HoldCo).",
    intuition:
      "Two kinds of priority not to mix up: contractual seniority (who is paid first within the same entity) and structural subordination (who is paid first depending on which legal entity owns the assets).",
    formula:
      "Contractual seniority (same entity): Senior secured > Senior unsecured > Senior subordinated > Equity\nStructural subordination: OpCo debt > HoldCo debt (assets sit at OpCo)",
    steps: [
      "Typical maturity order (shortest to longest): Revolver → Term Loan B → Senior Notes → Senior Subordinated Notes.",
      "Bank debt (revolver, term loan): traditional lenders, strict maintenance covenants (quarterly tests), mandatory amortisation (~1%/year for a TLB, final bullet).",
      "High yield bonds: institutional lenders, more flexible incurrence covenants (tested only on an event), no mandatory amortisation before maturity, but call protection.",
      "The revolver is usually undrawn at close — a liquidity cushion (seasonal NWC, unexpected CapEx), with a commitment fee on the unused portion.",
      "Bridge loan: temporary financing (≤ 1 year) until permanent take-out — a conversion fee applies if it stays outstanding beyond that.",
    ],
    example: {
      label: "Quick example",
      body: "Typical structure: Revolver (undrawn, 5-6 year maturity) → Term Loan B (7-year maturity, 1%/year amort.) → Senior Notes (7-10 year maturity, no amort. before due date, call protection). In default, the revolver and TLB are repaid before Senior Notes.",
    },
    interview:
      "Distinguishing maintenance covenants (bank, tested continuously) from incurrence covenants (high yield, tested only on an event) is a point the book tests explicitly — and why PE funds like HY flexibility despite a higher cost.",
    table: {
      headers: ["Instrument", "Typical lender", "Covenants", "Amortisation", "Relative cost"],
      rows: [
        ["Revolver", "Commercial banks", "Maintenance", "None (liquidity line)", "Cheapest (often undrawn)"],
        ["Term Loan A/B", "Banks / institutions", "Maintenance", "~1%/year + final bullet", "Moderate"],
        [
          "Senior Notes (High Yield)",
          "Bond investors",
          "Incurrence (more flexible)",
          "None before maturity",
          "Higher, but flexible",
        ],
        [
          "Senior Subordinated Notes",
          "Bond investors",
          "Incurrence",
          "None before maturity",
          "Highest (junior)",
        ],
        ["Mezzanine / PIK", "Mezzanine funds", "Incurrence", "None, interest can PIK", "High (10-15%), debt/equity hybrid"],
      ],
    },
    pitfalls: [
      "Confusing contractual seniority (same entity) with structural subordination (different entities, OpCo vs HoldCo)",
      "Assuming the revolver is automatically drawn at close — it is mainly a liquidity cushion",
      "Forgetting high-yield call protection, which limits a fast refinance if rates fall",
      "Confusing maintenance covenants (bank, strict) with incurrence covenants (high yield, flexible)",
    ],
  },
  {
    id: "c29",
    category: "ma",
    title: "Stock Deal vs Asset Deal: Tax Structuring of an Acquisition",
    simple:
      "Buying a company is not always buying the shares: you can also buy the assets one by one. The choice changes who pays how much tax, and who bears hidden risks (litigation, unidentified liabilities).",
    intuition:
      "Stock deal = the buyer takes everything, including unknown liabilities, but the deal is simpler and often less taxed for the seller. Asset deal = the buyer chooses what it takes, limits risk, and can tax-step-up the assets — more complex, sometimes more taxed for the seller (possible double tax).",
    formula:
      "Inside basis = tax basis of the company's assets\nOutside basis = tax basis of the company's shares\nDTL = (Tangible write-up + Intangible write-up) × Tax rate",
    steps: [
      "US framework (IRC, buy-side chapter of the book). In France/Europe: no 338(h)(10); look at transfer taxes, merger mali/boni, tax consolidation. The stock vs asset principle and the step-up still translate; the precise devices do not.",
      "Stock deal (share purchase): the target becomes a 100% subsidiary; the acquirer assumes all liabilities (known and unknown). Most common structure for US C Corps.",
      "Asset deal (asset purchase): the target legal entity continues to exist; the buyer chooses assumed assets and liabilities — protects against hidden liabilities, more complex to document.",
      "Tax step-up (asset deal): the buyer revalues the tax basis of assets to fair value → tax-deductible D&A over the step-up period, a real cash benefit.",
      "338(h)(10) (US, group subsidiary): hybrid — stock deal legally, asset deal for tax (step-up allowed). Joint buyer/seller consent; the buyer often pays more in exchange for the step-up.",
      "DTL: in a stock deal, GAAP write-up amortisation is not tax-deductible → book/tax basis gap → deferred tax liability.",
    ],
    example: {
      label: "Quick example",
      body: "Asset deal with a €550m step-up (tangible + intangible), 25% tax → €137.5m DTL added to liabilities. That step-up generates tax-deductible D&A — unlike a classic stock deal where that D&A is not deductible.",
    },
    interview:
      "Sellers often prefer a stock deal paid in paper: capital-gains tax can be deferred. Double taxation (company then shareholders on distribution) is an asset-deal-specific risk. Do not paste US 338(h)(10) onto a French deal.",
    table: {
      headers: ["Criterion", "Stock Deal", "Asset Deal"],
      rows: [
        ["Target entity", "Disappears (acquirer subsidiary)", "Continues to exist legally"],
        ["Liabilities assumed", "All, including unknown", "Only those specified in the contract"],
        ["Tax step-up", "No (except 338(h)(10))", "Yes — tax basis revalued"],
        [
          "Double-tax risk",
          "No",
          "Yes, if sale proceeds are distributed to shareholders",
        ],
        ["Complexity", "Simpler", "More complex (asset-by-asset transfer)"],
        [
          "Typical preference",
          "Seller (simplicity, tax deferral if stock)",
          "Buyer (less risk, deductible step-up)",
        ],
        ["Most common structure (US C Corp)", "Stock deal", "—"],
      ],
    },
    pitfalls: [
      "Assuming an asset step-up is automatic in a classic stock deal — only via a specific election (338(h)(10) in the US, no direct French equivalent)",
      "Confusing inside basis (tax basis of assets) with outside basis (tax basis of shares)",
      "Forgetting double-tax risk in an asset deal if sale proceeds are then distributed to shareholders",
      "Pasting US textbook tax rules onto a French/European deal without checking local equivalents",
    ],
  },
];
