/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PyramidRouteImport } from './routes/pyramid'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as GlossaireRouteImport } from './routes/glossaire'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as ExcelRouteImport } from './routes/excel'
import { Route as CvRouteImport } from './routes/cv'
import { Route as ActualiteRouteImport } from './routes/actualite'
import { Route as AccretionRouteImport } from './routes/accretion'
import { Route as IndexRouteImport } from './routes/index'

const PyramidRoute = PyramidRouteImport.update({
  id: '/pyramid',
  path: '/pyramid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaireRoute = GlossaireRouteImport.update({
  id: '/glossaire',
  path: '/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcelRoute = ExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualiteRoute = ActualiteRouteImport.update({
  id: '/actualite',
  path: '/actualite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccretionRoute = AccretionRouteImport.update({
  id: '/accretion',
  path: '/accretion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accretion': typeof AccretionRoute
  '/actualite': typeof ActualiteRoute
  '/cv': typeof CvRoute
  '/excel': typeof ExcelRoute
  '/flashcards': typeof FlashcardsRoute
  '/glossaire': typeof GlossaireRoute
  '/interview': typeof InterviewRoute
  '/profil': typeof ProfilRoute
  '/pyramid': typeof PyramidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accretion': typeof AccretionRoute
  '/actualite': typeof ActualiteRoute
  '/cv': typeof CvRoute
  '/excel': typeof ExcelRoute
  '/flashcards': typeof FlashcardsRoute
  '/glossaire': typeof GlossaireRoute
  '/interview': typeof InterviewRoute
  '/profil': typeof ProfilRoute
  '/pyramid': typeof PyramidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accretion': typeof AccretionRoute
  '/actualite': typeof ActualiteRoute
  '/cv': typeof CvRoute
  '/excel': typeof ExcelRoute
  '/flashcards': typeof FlashcardsRoute
  '/glossaire': typeof GlossaireRoute
  '/interview': typeof InterviewRoute
  '/profil': typeof ProfilRoute
  '/pyramid': typeof PyramidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accretion'
    | '/actualite'
    | '/cv'
    | '/excel'
    | '/flashcards'
    | '/glossaire'
    | '/interview'
    | '/profil'
    | '/pyramid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accretion'
    | '/actualite'
    | '/cv'
    | '/excel'
    | '/flashcards'
    | '/glossaire'
    | '/interview'
    | '/profil'
    | '/pyramid'
  id:
    | '__root__'
    | '/'
    | '/accretion'
    | '/actualite'
    | '/cv'
    | '/excel'
    | '/flashcards'
    | '/glossaire'
    | '/interview'
    | '/profil'
    | '/pyramid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccretionRoute: typeof AccretionRoute
  ActualiteRoute: typeof ActualiteRoute
  CvRoute: typeof CvRoute
  ExcelRoute: typeof ExcelRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GlossaireRoute: typeof GlossaireRoute
  InterviewRoute: typeof InterviewRoute
  ProfilRoute: typeof ProfilRoute
  PyramidRoute: typeof PyramidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pyramid': {
      id: '/pyramid'
      path: '/pyramid'
      fullPath: '/pyramid'
      preLoaderRoute: typeof PyramidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossaire': {
      id: '/glossaire'
      path: '/glossaire'
      fullPath: '/glossaire'
      preLoaderRoute: typeof GlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excel': {
      id: '/excel'
      path: '/excel'
      fullPath: '/excel'
      preLoaderRoute: typeof ExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualite': {
      id: '/actualite'
      path: '/actualite'
      fullPath: '/actualite'
      preLoaderRoute: typeof ActualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accretion': {
      id: '/accretion'
      path: '/accretion'
      fullPath: '/accretion'
      preLoaderRoute: typeof AccretionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccretionRoute: AccretionRoute,
  ActualiteRoute: ActualiteRoute,
  CvRoute: CvRoute,
  ExcelRoute: ExcelRoute,
  FlashcardsRoute: FlashcardsRoute,
  GlossaireRoute: GlossaireRoute,
  InterviewRoute: InterviewRoute,
  ProfilRoute: ProfilRoute,
  PyramidRoute: PyramidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
