/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PyramidRouteImport } from './routes/pyramid'
import { Route as GlossaireRouteImport } from './routes/glossaire'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'

const PyramidRoute = PyramidRouteImport.update({
  id: '/pyramid',
  path: '/pyramid',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaireRoute = GlossaireRouteImport.update({
  id: '/glossaire',
  path: '/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/glossaire': typeof GlossaireRoute
  '/pyramid': typeof PyramidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/glossaire': typeof GlossaireRoute
  '/pyramid': typeof PyramidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/glossaire': typeof GlossaireRoute
  '/pyramid': typeof PyramidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cv' | '/glossaire' | '/pyramid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cv' | '/glossaire' | '/pyramid'
  id: '__root__' | '/' | '/cv' | '/glossaire' | '/pyramid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  GlossaireRoute: typeof GlossaireRoute
  PyramidRoute: typeof PyramidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pyramid': {
      id: '/pyramid'
      path: '/pyramid'
      fullPath: '/pyramid'
      preLoaderRoute: typeof PyramidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossaire': {
      id: '/glossaire'
      path: '/glossaire'
      fullPath: '/glossaire'
      preLoaderRoute: typeof GlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  GlossaireRoute: GlossaireRoute,
  PyramidRoute: PyramidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
